In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('air_data.csv', sep=";")
df

,Country Code,City,Location,Coordinates,Pollutant,Source Name,Unit,Value,Last Updated,Country Label
0,DE,Manfred Lotz,"Cottbus, W.-Külz-Str.","51.75413,14.325549",PM2.5,EEA Germany,µg/m³,21.7,2016-12-21T12:00:00+01:00,Germany
1,ES,Castellón/Castelló,ES1969A,"39.8236111095,-0.24444444",NO2,EEA Spain,µg/m³,1.0,2021-07-13T08:00:00+02:00,Spain
2,ES,Valencia/València,ES1885A,"39.4802777695,-0.33638888",SO2,EEA Spain,µg/m³,5.0,2021-08-06T11:00:00+02:00,Spain
3,ES,Alicante/Alacant,ES2008A,"37.9911111095,-0.69",PM2.5,EEA Spain,µg/m³,9.0,2021-08-06T11:00:00+02:00,Spain
4,ES,Alicante/Alacant,ES1968A,"38.3511111095,-0.51388888",PM10,EEA Spain,µg/m³,1.0,2021-08-06T11:00:00+02:00,Spain
...,...,...,...,...,...,...,...,...,...,...
40446,US,BERNALILLO,WESTSIDE - 9 Mile,"35.064098,-106.761292",PM10,AirNow,µg/m³,10.0,2020-07-17T14:00:00+02:00,United States
40447,US,Asheville,Skyland DRR,"35.481861,-82.509861",SO2,AirNow,ppm,0.0,2020-07-02T12:00:00+02:00,United States
40448,US,San Antonio,San Antonio IH35 C10,"29.5294,-98.39139",PM2.5,AirNow,µg/m³,6.0,2020-06-26T01:00:00+02:00,United States
40449,US,Cleveland-Elyria-Mentor,Cleveland Near Road,"41.4409,-81.4949",PM2.5,AirNow,µg/m³,15.3,2020-05-26T16:00:00+02:00,United States
40450,US,Seattle-Tacoma-Bellevue,Auburn M St SE,"47.2875,-122.2144",PM2.5,AirNow,µg/m³,3.0,2020-04-07T18:00:00+02:00,United States

In [7]:
#1) Supprimer les données qui ne concernent pas la journée du 06-08-2021.
from datetime import datetime

df["Last Update Day"] = df["Last Updated"].str[:10]
df["Last Update Day"] = pd.to_datetime(df["Last Update Day"],format='%Y-%m-%d',errors='coerce')
df = df[df.columns[[0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 9]]]
df = df.loc[df['Last Update Day'] == "2021-08-06"]
df

KeyError: 'Last Updated'

In [4]:
df = df["Last Updated"].str.contains('2021-08-06').value_counts()
df

True     24287
False    16164
Name: Last Updated, dtype: int64

In [ ]:
# Supprimer la Location :
df = df.drop(columns=["Location"])
df

In [ ]:
# Put the "City" column Capitalized:
df['City'] = list(map(lambda x: str(x).capitalize(), df['City']))
df

In [ ]:
# Keep the city names before the "/" - delete what's after with regex:
df['City'] = df['City'].str.replace(r'\/.*$',r"", regex=True)
df

In [ ]:
# Delete row if "City" has more than one city: 
df = df[~df['City'].str.contains('-')]
df

In [ ]:
#2) Supprimer les données qui sont illisibles et pour lesquelles on ne comprend pas la ville concernée.
#Etape 1 : supprimer les NA qui nuisent à l'analyse (1/2)
print(df.isnull().sum())
#print(df[df['Country Label'].isnull()])
#print(df[df['City'].isnull()])

In [ ]:
#2) Supprimer les données qui sont illisibles et pour lesquelles on ne comprend pas la ville concernée.
#Etape 1 : supprimer les NA qui nuisent à l'analyse (2/2)
df = df.dropna().copy()
df

In [ ]:

#2) Supprimer les données qui sont illisibles et pour lesquelles on ne comprend pas la ville concernée.
#Etape 2 : regarder à quoi ressemblent les valeurs de la colonne City
df.City.tolist()

In [ ]:
#2) Supprimer les données qui sont illisibles et pour lesquelles on ne comprend pas la ville concernée.
#Etape 3 : supprimer les lignes avec des villes qui ne sont pas écrites avec l'alphabet latin
import re

df["City"] = df["City"].apply(str)
df = df[df["City"].str.contains(r'[A-Za-zÀ-ÿ/-]')]
print(df.City.tolist())